/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\VSCode\\vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-2378275d",
    path: "/cloudnative/docker/Docker%E5%85%A5%E9%97%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2378275d").then(next)
    },
  },
  {
    path: "/cloudnative/docker/Docker入门.html",
    redirect: "/cloudnative/docker/Docker%E5%85%A5%E9%97%A8.html"
  },
  {
    path: "/cloudnative/docker/Docker入门.html",
    redirect: "/cloudnative/docker/Docker%E5%85%A5%E9%97%A8.html"
  },
  {
    name: "v-de4f0cde",
    path: "/database/Redis/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-de4f0cde").then(next)
    },
  },
  {
    path: "/database/Redis/index.html",
    redirect: "/database/Redis/"
  },
  {
    name: "v-6c780946",
    path: "/database/MySQL/MySQL%E7%AE%80%E4%BB%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c780946").then(next)
    },
  },
  {
    path: "/database/MySQL/MySQL简介.html",
    redirect: "/database/MySQL/MySQL%E7%AE%80%E4%BB%8B.html"
  },
  {
    path: "/database/MySQL/MySQL简介.html",
    redirect: "/database/MySQL/MySQL%E7%AE%80%E4%BB%8B.html"
  },
  {
    name: "v-04f476dd",
    path: "/cloudnative/kubernetes/kubernetes%E5%85%A5%E9%97%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04f476dd").then(next)
    },
  },
  {
    path: "/cloudnative/kubernetes/kubernetes入门.html",
    redirect: "/cloudnative/kubernetes/kubernetes%E5%85%A5%E9%97%A8.html"
  },
  {
    path: "/cloudnative/kubernetes/kubernetes入门.html",
    redirect: "/cloudnative/kubernetes/kubernetes%E5%85%A5%E9%97%A8.html"
  },
  {
    name: "v-031b80f5",
    path: "/get-start/markdown/md%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-031b80f5").then(next)
    },
  },
  {
    path: "/get-start/markdown/md快速入门.html",
    redirect: "/get-start/markdown/md%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html"
  },
  {
    path: "/get-start/markdown/md快速入门.html",
    redirect: "/get-start/markdown/md%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html"
  },
  {
    name: "v-44aefb24",
    path: "/get-start/vuepress%E5%85%A5%E9%97%A8/vuepress%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44aefb24").then(next)
    },
  },
  {
    path: "/get-start/vuepress入门/vuepress快速上手.html",
    redirect: "/get-start/vuepress%E5%85%A5%E9%97%A8/vuepress%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B.html"
  },
  {
    path: "/get-start/vuepress入门/vuepress快速上手.html",
    redirect: "/get-start/vuepress%E5%85%A5%E9%97%A8/vuepress%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B.html"
  },
  {
    name: "v-074dedae",
    path: "/get-start/vuepress%E5%85%A5%E9%97%A8/%E4%BD%BF%E7%94%A8docker%E9%83%A8%E7%BD%B2vuepress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-074dedae").then(next)
    },
  },
  {
    path: "/get-start/vuepress入门/使用docker部署vuepress.html",
    redirect: "/get-start/vuepress%E5%85%A5%E9%97%A8/%E4%BD%BF%E7%94%A8docker%E9%83%A8%E7%BD%B2vuepress.html"
  },
  {
    path: "/get-start/vuepress入门/使用docker部署vuepress.html",
    redirect: "/get-start/vuepress%E5%85%A5%E9%97%A8/%E4%BD%BF%E7%94%A8docker%E9%83%A8%E7%BD%B2vuepress.html"
  },
  {
    name: "v-ad4ce3b2",
    path: "/database/Redis/Redis%E7%9A%84%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ad4ce3b2").then(next)
    },
  },
  {
    path: "/database/Redis/Redis的数据结构.html",
    redirect: "/database/Redis/Redis%E7%9A%84%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    path: "/database/Redis/Redis的数据结构.html",
    redirect: "/database/Redis/Redis%E7%9A%84%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    name: "v-749a2f88",
    path: "/java/java%E5%9F%BA%E7%A1%80/Java%E7%9A%84%E5%8F%98%E9%87%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-749a2f88").then(next)
    },
  },
  {
    path: "/java/java基础/Java的变量.html",
    redirect: "/java/java%E5%9F%BA%E7%A1%80/Java%E7%9A%84%E5%8F%98%E9%87%8F.html"
  },
  {
    path: "/java/java基础/Java的变量.html",
    redirect: "/java/java%E5%9F%BA%E7%A1%80/Java%E7%9A%84%E5%8F%98%E9%87%8F.html"
  },
  {
    name: "v-2dddb41d",
    path: "/java/java%E5%9F%BA%E7%A1%80/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2dddb41d").then(next)
    },
  },
  {
    path: "/java/java基础/",
    redirect: "/java/java%E5%9F%BA%E7%A1%80/"
  },
  {
    path: "/java/java%E5%9F%BA%E7%A1%80/index.html",
    redirect: "/java/java%E5%9F%BA%E7%A1%80/"
  },
  {
    path: "/java/java基础/",
    redirect: "/java/java%E5%9F%BA%E7%A1%80/"
  },
  {
    name: "v-e381f5f4",
    path: "/java/java%E5%9F%BA%E7%A1%80/Java%E4%B8%AD%E7%9A%84%E6%95%B0%E7%BB%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e381f5f4").then(next)
    },
  },
  {
    path: "/java/java基础/Java中的数组.html",
    redirect: "/java/java%E5%9F%BA%E7%A1%80/Java%E4%B8%AD%E7%9A%84%E6%95%B0%E7%BB%84.html"
  },
  {
    path: "/java/java基础/Java中的数组.html",
    redirect: "/java/java%E5%9F%BA%E7%A1%80/Java%E4%B8%AD%E7%9A%84%E6%95%B0%E7%BB%84.html"
  },
  {
    name: "v-0f810786",
    path: "/java/java%E9%AB%98%E7%BA%A7/Java%E5%A4%9A%E7%BA%BF%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f810786").then(next)
    },
  },
  {
    path: "/java/java高级/Java多线程.html",
    redirect: "/java/java%E9%AB%98%E7%BA%A7/Java%E5%A4%9A%E7%BA%BF%E7%A8%8B.html"
  },
  {
    path: "/java/java高级/Java多线程.html",
    redirect: "/java/java%E9%AB%98%E7%BA%A7/Java%E5%A4%9A%E7%BA%BF%E7%A8%8B.html"
  },
  {
    name: "v-60e69aca",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60e69aca").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-5c3f2240",
    path: "/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c3f2240").then(next)
    },
  },
  {
    name: "v-3b6273ea",
    path: "/java/java%E5%9F%BA%E7%A1%80/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b6273ea").then(next)
    },
  },
  {
    path: "/java/java基础/面向对象.html",
    redirect: "/java/java%E5%9F%BA%E7%A1%80/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html"
  },
  {
    path: "/java/java基础/面向对象.html",
    redirect: "/java/java%E5%9F%BA%E7%A1%80/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html"
  },
  {
    name: "v-15a2cedc",
    path: "/java/java%E9%AB%98%E7%BA%A7/Java%E9%9B%86%E5%90%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15a2cedc").then(next)
    },
  },
  {
    path: "/java/java高级/Java集合.html",
    redirect: "/java/java%E9%AB%98%E7%BA%A7/Java%E9%9B%86%E5%90%88.html"
  },
  {
    path: "/java/java高级/Java集合.html",
    redirect: "/java/java%E9%AB%98%E7%BA%A7/Java%E9%9B%86%E5%90%88.html"
  },
  {
    name: "v-b2baac44",
    path: "/network/http/HTTP%E5%B8%B8%E8%A7%81%E7%9F%A5%E8%AF%86%E7%82%B9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b2baac44").then(next)
    },
  },
  {
    path: "/network/http/HTTP常见知识点.html",
    redirect: "/network/http/HTTP%E5%B8%B8%E8%A7%81%E7%9F%A5%E8%AF%86%E7%82%B9.html"
  },
  {
    path: "/network/http/HTTP常见知识点.html",
    redirect: "/network/http/HTTP%E5%B8%B8%E8%A7%81%E7%9F%A5%E8%AF%86%E7%82%B9.html"
  },
  {
    name: "v-103622ea",
    path: "/network/http/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-103622ea").then(next)
    },
  },
  {
    path: "/network/http/index.html",
    redirect: "/network/http/"
  },
  {
    name: "v-5101ce4d",
    path: "/network/http/TCP%E5%8D%8F%E8%AE%AE%E8%AF%A6%E8%A7%A3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5101ce4d").then(next)
    },
  },
  {
    path: "/network/http/TCP协议详解.html",
    redirect: "/network/http/TCP%E5%8D%8F%E8%AE%AE%E8%AF%A6%E8%A7%A3.html"
  },
  {
    path: "/network/http/TCP协议详解.html",
    redirect: "/network/http/TCP%E5%8D%8F%E8%AE%AE%E8%AF%A6%E8%A7%A3.html"
  },
  {
    name: "v-c257a9d2",
    path: "/network/tcp/TCP%E8%AF%A6%E8%A7%A3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c257a9d2").then(next)
    },
  },
  {
    path: "/network/tcp/TCP详解.html",
    redirect: "/network/tcp/TCP%E8%AF%A6%E8%A7%A3.html"
  },
  {
    path: "/network/tcp/TCP详解.html",
    redirect: "/network/tcp/TCP%E8%AF%A6%E8%A7%A3.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]