/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\nodejs\\yarn_global\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-b832ecce",
    path: "/Java/Java%E5%A4%9A%E7%BA%BF%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b832ecce").then(next)
    },
  },
  {
    path: "/Java/Java多线程.html",
    redirect: "/Java/Java%E5%A4%9A%E7%BA%BF%E7%A8%8B.html"
  },
  {
    path: "/Java/Java多线程.html",
    redirect: "/Java/Java%E5%A4%9A%E7%BA%BF%E7%A8%8B.html"
  },
  {
    name: "v-6960f2c2",
    path: "/Java/Java%E9%9B%86%E5%90%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6960f2c2").then(next)
    },
  },
  {
    path: "/Java/Java集合.html",
    redirect: "/Java/Java%E9%9B%86%E5%90%88.html"
  },
  {
    path: "/Java/Java集合.html",
    redirect: "/Java/Java%E9%9B%86%E5%90%88.html"
  },
  {
    name: "v-3239f1db",
    path: "/Java/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3239f1db").then(next)
    },
  },
  {
    path: "/Java/面向对象.html",
    redirect: "/Java/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html"
  },
  {
    path: "/Java/面向对象.html",
    redirect: "/Java/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html"
  },
  {
    name: "v-60e69aca",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60e69aca").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-5c3f2240",
    path: "/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c3f2240").then(next)
    },
  },
  {
    name: "v-782676b0",
    path: "/Redis/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-782676b0").then(next)
    },
  },
  {
    path: "/Redis/index.html",
    redirect: "/Redis/"
  },
  {
    name: "v-199dc994",
    path: "/Redis/Redis%E7%9A%84%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-199dc994").then(next)
    },
  },
  {
    path: "/Redis/Redis的数据结构.html",
    redirect: "/Redis/Redis%E7%9A%84%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    path: "/Redis/Redis的数据结构.html",
    redirect: "/Redis/Redis%E7%9A%84%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    name: "v-35fceb26",
    path: "/http/HTTP%E5%B8%B8%E8%A7%81%E7%9F%A5%E8%AF%86%E7%82%B9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35fceb26").then(next)
    },
  },
  {
    path: "/http/HTTP常见知识点.html",
    redirect: "/http/HTTP%E5%B8%B8%E8%A7%81%E7%9F%A5%E8%AF%86%E7%82%B9.html"
  },
  {
    path: "/http/HTTP常见知识点.html",
    redirect: "/http/HTTP%E5%B8%B8%E8%A7%81%E7%9F%A5%E8%AF%86%E7%82%B9.html"
  },
  {
    name: "v-1907ae84",
    path: "/http/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1907ae84").then(next)
    },
  },
  {
    path: "/http/index.html",
    redirect: "/http/"
  },
  {
    name: "v-2a45a31c",
    path: "/http/TCP%E5%8D%8F%E8%AE%AE%E8%AF%A6%E8%A7%A3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a45a31c").then(next)
    },
  },
  {
    path: "/http/TCP协议详解.html",
    redirect: "/http/TCP%E5%8D%8F%E8%AE%AE%E8%AF%A6%E8%A7%A3.html"
  },
  {
    path: "/http/TCP协议详解.html",
    redirect: "/http/TCP%E5%8D%8F%E8%AE%AE%E8%AF%A6%E8%A7%A3.html"
  },
  {
    name: "v-15fec9c2",
    path: "/markdown/md%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15fec9c2").then(next)
    },
  },
  {
    path: "/markdown/md快速入门.html",
    redirect: "/markdown/md%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html"
  },
  {
    path: "/markdown/md快速入门.html",
    redirect: "/markdown/md%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html"
  },
  {
    name: "v-58602bfe",
    path: "/Java/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58602bfe").then(next)
    },
  },
  {
    path: "/Java/index.html",
    redirect: "/Java/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]