/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "somnus",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "somnus-wang"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "vuepress介绍"
      }
    ],
    [
      "meta",
      {
        "name": "referrer",
        "content": "no-referrer"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/123.png",
        "heroText": "Somnus Space",
        "tagline": "somnus的个人笔记",
        "actionText": "快速开始 →",
        "actionLink": "/about/",
        "footer": "SCU Licensed | Copyright © 2022-present Somnus-wang & Lj-Z"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-60e69aca",
      "path": "/",
      "lastUpdated": "2022年5月2日 17:52",
      "lastUpdatedTimestamp": 1651485172000
    },
    {
      "title": "设计模式概述",
      "frontmatter": {},
      "regularPath": "/backend/DesignPatterns/",
      "relativePath": "backend/DesignPatterns/README.md",
      "key": "v-2d0c6c2a",
      "path": "/backend/DesignPatterns/",
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-5c3f2240",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        }
      ],
      "lastUpdated": "2022年4月21日 17:59",
      "lastUpdatedTimestamp": 1650535194000
    },
    {
      "title": "多线程",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "'",
        "7": "多",
        "8": "线",
        "9": "程",
        "10": "'"
      },
      "regularPath": "/backend/Java/Java%E5%A4%9A%E7%BA%BF%E7%A8%8B.html",
      "relativePath": "backend/Java/Java多线程.md",
      "key": "v-3119ae96",
      "path": "/backend/Java/Java%E5%A4%9A%E7%BA%BF%E7%A8%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "Java的变量",
      "frontmatter": {},
      "regularPath": "/backend/Java/Java%E7%9A%84%E5%8F%98%E9%87%8F.html",
      "relativePath": "backend/Java/Java的变量.md",
      "key": "v-0939a28c",
      "path": "/backend/Java/Java%E7%9A%84%E5%8F%98%E9%87%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "数据类型",
          "slug": "数据类型"
        },
        {
          "level": 2,
          "title": "基本数据类型转换",
          "slug": "基本数据类型转换"
        },
        {
          "level": 2,
          "title": "String类型变量的使用",
          "slug": "string类型变量的使用"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "==和equals的区别",
      "frontmatter": {},
      "regularPath": "/backend/Java/==%E5%92%8Cequals%E7%9A%84%E5%8C%BA%E5%88%AB.html",
      "relativePath": "backend/Java/==和equals的区别.md",
      "key": "v-48bc3c18",
      "path": "/backend/Java/==%E5%92%8Cequals%E7%9A%84%E5%8C%BA%E5%88%AB.html",
      "headers": [
        {
          "level": 2,
          "title": "==",
          "slug": ""
        },
        {
          "level": 2,
          "title": "equals",
          "slug": "equals"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "Java中的数组",
      "frontmatter": {},
      "regularPath": "/backend/Java/Java%E4%B8%AD%E7%9A%84%E6%95%B0%E7%BB%84.html",
      "relativePath": "backend/Java/Java中的数组.md",
      "key": "v-97e2f914",
      "path": "/backend/Java/Java%E4%B8%AD%E7%9A%84%E6%95%B0%E7%BB%84.html",
      "headers": [
        {
          "level": 2,
          "title": "数组概述",
          "slug": "数组概述"
        },
        {
          "level": 2,
          "title": "数组的内存解析",
          "slug": "数组的内存解析"
        },
        {
          "level": 2,
          "title": "二维数组的解析",
          "slug": "二维数组的解析"
        },
        {
          "level": 2,
          "title": "数组中涉及到的常见算法：排序算法",
          "slug": "数组中涉及到的常见算法-排序算法"
        },
        {
          "level": 3,
          "title": "冒泡排序",
          "slug": "冒泡排序"
        },
        {
          "level": 3,
          "title": "快速排序",
          "slug": "快速排序"
        },
        {
          "level": 3,
          "title": "Arrays工具类的使用",
          "slug": "arrays工具类的使用"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "单例模式",
      "frontmatter": {},
      "regularPath": "/backend/DesignPatterns/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F.html",
      "relativePath": "backend/DesignPatterns/单例模式.md",
      "key": "v-4ee6438a",
      "path": "/backend/DesignPatterns/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F.html",
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "Java集合",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "'",
        "7": "J",
        "8": "a",
        "9": "v",
        "10": "a",
        "11": "集",
        "12": "合",
        "13": "'"
      },
      "regularPath": "/backend/Java/Java%E9%9B%86%E5%90%88.html",
      "relativePath": "backend/Java/Java集合.md",
      "key": "v-2f32e772",
      "path": "/backend/Java/Java%E9%9B%86%E5%90%88.html",
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "Hello,Java!",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "j",
        "7": "a",
        "8": "v",
        "9": "a"
      },
      "regularPath": "/backend/Java/",
      "relativePath": "backend/Java/README.md",
      "key": "v-d891d5ea",
      "path": "/backend/Java/",
      "headers": [
        {
          "level": 2,
          "title": "Hello,Java!",
          "slug": "hello-java"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "Shell入门",
      "frontmatter": {},
      "regularPath": "/backend/Java/Shell%E5%85%A5%E9%97%A8.html",
      "relativePath": "backend/Java/Shell入门.md",
      "key": "v-2dcf3f67",
      "path": "/backend/Java/Shell%E5%85%A5%E9%97%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "脚本格式",
          "slug": "脚本格式"
        },
        {
          "level": 2,
          "title": "Shell中的变量",
          "slug": "shell中的变量"
        },
        {
          "level": 3,
          "title": "1.常用系统变量",
          "slug": "_1-常用系统变量"
        },
        {
          "level": 3,
          "title": "2.自定义变量",
          "slug": "_2-自定义变量"
        },
        {
          "level": 3,
          "title": "3.注意事项",
          "slug": "_3-注意事项"
        },
        {
          "level": 3,
          "title": "4.特殊变量",
          "slug": "_4-特殊变量"
        },
        {
          "level": 3,
          "title": "5.运算符",
          "slug": "_5-运算符"
        },
        {
          "level": 3,
          "title": "6.条件判断",
          "slug": "_6-条件判断"
        },
        {
          "level": 3,
          "title": "7.流程控制",
          "slug": "_7-流程控制"
        },
        {
          "level": 3,
          "title": "8.read读取控制台输入",
          "slug": "_8-read读取控制台输入"
        },
        {
          "level": 3,
          "title": "9.函数",
          "slug": "_9-函数"
        },
        {
          "level": 3,
          "title": "Shell工具",
          "slug": "shell工具"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "static关键字",
      "frontmatter": {},
      "regularPath": "/backend/Java/static%E5%85%B3%E9%94%AE%E5%AD%97.html",
      "relativePath": "backend/Java/static关键字.md",
      "key": "v-2cbadf4e",
      "path": "/backend/Java/static%E5%85%B3%E9%94%AE%E5%AD%97.html",
      "headers": [
        {
          "level": 2,
          "title": "static的使用",
          "slug": "static的使用"
        },
        {
          "level": 3,
          "title": "static修饰属性",
          "slug": "static修饰属性"
        },
        {
          "level": 3,
          "title": "static修饰方法",
          "slug": "static修饰方法"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "面向对象",
      "frontmatter": {},
      "regularPath": "/backend/Java/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html",
      "relativePath": "backend/Java/面向对象.md",
      "key": "v-7aa1d06e",
      "path": "/backend/Java/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html",
      "headers": [
        {
          "level": 2,
          "title": "面向过程（POP）和面向对象（OOP）",
          "slug": "面向过程-pop-和面向对象-oop"
        },
        {
          "level": 2,
          "title": "类的结构",
          "slug": "类的结构"
        },
        {
          "level": 3,
          "title": "方法的重载（overload）",
          "slug": "方法的重载-overload"
        },
        {
          "level": 3,
          "title": "方法参数的值传递机制",
          "slug": "方法参数的值传递机制"
        },
        {
          "level": 2,
          "title": "JavaBean",
          "slug": "javabean"
        },
        {
          "level": 2,
          "title": "面向对象的三大特征",
          "slug": "面向对象的三大特征"
        },
        {
          "level": 3,
          "title": "封装性",
          "slug": "封装性"
        },
        {
          "level": 3,
          "title": "继承性",
          "slug": "继承性"
        },
        {
          "level": 3,
          "title": "子类对象实例化过程",
          "slug": "子类对象实例化过程"
        },
        {
          "level": 3,
          "title": "多态性",
          "slug": "多态性"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "MySQL",
      "frontmatter": {},
      "regularPath": "/backend/MySQL/MySQL%E7%AE%80%E4%BB%8B.html",
      "relativePath": "backend/MySQL/MySQL简介.md",
      "key": "v-6e98a3c4",
      "path": "/backend/MySQL/MySQL%E7%AE%80%E4%BB%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是MySQL",
          "slug": "什么是mysql"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "MySQL数据库概述",
      "frontmatter": {},
      "regularPath": "/backend/MySQL/",
      "relativePath": "backend/MySQL/README.md",
      "key": "v-1c5f1a85",
      "path": "/backend/MySQL/",
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "Redis概述",
      "frontmatter": {},
      "regularPath": "/backend/Redis/",
      "relativePath": "backend/Redis/README.md",
      "key": "v-dae45c5a",
      "path": "/backend/Redis/",
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "Redis数据结构",
      "frontmatter": {},
      "regularPath": "/backend/Redis/Redis%E7%9A%84%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html",
      "relativePath": "backend/Redis/Redis的数据结构.md",
      "key": "v-32e91111",
      "path": "/backend/Redis/Redis%E7%9A%84%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html",
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "Shell概述",
      "frontmatter": {},
      "regularPath": "/backend/Shell/",
      "relativePath": "backend/Shell/README.md",
      "key": "v-be4686ae",
      "path": "/backend/Shell/",
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "Web服务器概述",
      "frontmatter": {},
      "regularPath": "/backend/webserver/",
      "relativePath": "backend/webserver/README.md",
      "key": "v-15d7715b",
      "path": "/backend/webserver/",
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "Shell入门",
      "frontmatter": {},
      "regularPath": "/backend/Shell/Shell%E5%85%A5%E9%97%A8.html",
      "relativePath": "backend/Shell/Shell入门.md",
      "key": "v-736700a3",
      "path": "/backend/Shell/Shell%E5%85%A5%E9%97%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "脚本格式",
          "slug": "脚本格式"
        },
        {
          "level": 2,
          "title": "Shell中的变量",
          "slug": "shell中的变量"
        },
        {
          "level": 3,
          "title": "1.常用系统变量",
          "slug": "_1-常用系统变量"
        },
        {
          "level": 3,
          "title": "2.自定义变量",
          "slug": "_2-自定义变量"
        },
        {
          "level": 3,
          "title": "3.注意事项",
          "slug": "_3-注意事项"
        },
        {
          "level": 3,
          "title": "4.特殊变量",
          "slug": "_4-特殊变量"
        },
        {
          "level": 3,
          "title": "5.运算符",
          "slug": "_5-运算符"
        },
        {
          "level": 3,
          "title": "6.条件判断",
          "slug": "_6-条件判断"
        },
        {
          "level": 3,
          "title": "7.流程控制",
          "slug": "_7-流程控制"
        },
        {
          "level": 3,
          "title": "8.read读取控制台输入",
          "slug": "_8-read读取控制台输入"
        },
        {
          "level": 3,
          "title": "9.函数",
          "slug": "_9-函数"
        },
        {
          "level": 3,
          "title": "Shell工具",
          "slug": "shell工具"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "Docker入门",
      "frontmatter": {},
      "regularPath": "/cloudnative/docker/Docker%E5%85%A5%E9%97%A8.html",
      "relativePath": "cloudnative/docker/Docker入门.md",
      "key": "v-2378275d",
      "path": "/cloudnative/docker/Docker%E5%85%A5%E9%97%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "Docker概念",
          "slug": "docker概念"
        },
        {
          "level": 2,
          "title": "安装Docker",
          "slug": "安装docker"
        },
        {
          "level": 3,
          "title": "Docker的架构",
          "slug": "docker的架构"
        },
        {
          "level": 2,
          "title": "Docker命令",
          "slug": "docker命令"
        },
        {
          "level": 3,
          "title": "Docker镜像相关命令",
          "slug": "docker镜像相关命令"
        },
        {
          "level": 3,
          "title": "Docker容器命令",
          "slug": "docker容器命令"
        },
        {
          "level": 2,
          "title": "Docker容器的数据卷",
          "slug": "docker容器的数据卷"
        },
        {
          "level": 3,
          "title": "配置数据卷",
          "slug": "配置数据卷"
        },
        {
          "level": 3,
          "title": "数据卷容器",
          "slug": "数据卷容器"
        },
        {
          "level": 2,
          "title": "Docker应用部署",
          "slug": "docker应用部署"
        },
        {
          "level": 2,
          "title": "Dockerfile",
          "slug": "dockerfile"
        },
        {
          "level": 3,
          "title": "docker镜像原理",
          "slug": "docker镜像原理"
        },
        {
          "level": 3,
          "title": "镜像制作",
          "slug": "镜像制作"
        },
        {
          "level": 2,
          "title": "Dockerfile案例",
          "slug": "dockerfile案例"
        },
        {
          "level": 2,
          "title": "Docker服务编排",
          "slug": "docker服务编排"
        },
        {
          "level": 3,
          "title": "Docker Compose",
          "slug": "docker-compose"
        },
        {
          "level": 2,
          "title": "Docker容器虚拟化与传统虚拟机比较",
          "slug": "docker容器虚拟化与传统虚拟机比较"
        }
      ],
      "lastUpdated": "2022年4月21日 17:59",
      "lastUpdatedTimestamp": 1650535194000
    },
    {
      "title": "Tomcat详解",
      "frontmatter": {},
      "regularPath": "/backend/webserver/Tomcat%E8%AF%A6%E8%A7%A3.html",
      "relativePath": "backend/webserver/Tomcat详解.md",
      "key": "v-a0fb218a",
      "path": "/backend/webserver/Tomcat%E8%AF%A6%E8%A7%A3.html",
      "headers": [
        {
          "level": 2,
          "title": "Tomcat基础",
          "slug": "tomcat基础"
        },
        {
          "level": 3,
          "title": "web概念",
          "slug": "web概念"
        },
        {
          "level": 2,
          "title": "Tomcat架构",
          "slug": "tomcat架构"
        },
        {
          "level": 3,
          "title": "Servlet容器工作流程",
          "slug": "servlet容器工作流程"
        },
        {
          "level": 3,
          "title": "Tomcat整体架构",
          "slug": "tomcat整体架构"
        },
        {
          "level": 3,
          "title": "连接器-Coyote",
          "slug": "连接器-coyote"
        },
        {
          "level": 3,
          "title": "容器-Catalina",
          "slug": "容器-catalina"
        },
        {
          "level": 2,
          "title": "Tomcat的启动流程",
          "slug": "tomcat的启动流程"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "Kubernetes概述",
      "frontmatter": {},
      "regularPath": "/cloudnative/kubernetes/",
      "relativePath": "cloudnative/kubernetes/README.md",
      "key": "v-64d46a6a",
      "path": "/cloudnative/kubernetes/",
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "Kubernetes",
      "frontmatter": {},
      "regularPath": "/cloudnative/kubernetes/kubernetes%E5%85%A5%E9%97%A8.html",
      "relativePath": "cloudnative/kubernetes/kubernetes入门.md",
      "key": "v-04f476dd",
      "path": "/cloudnative/kubernetes/kubernetes%E5%85%A5%E9%97%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "Kubernetes简介",
          "slug": "kubernetes简介"
        }
      ],
      "lastUpdated": "2022年4月21日 17:59",
      "lastUpdatedTimestamp": 1650535194000
    },
    {
      "title": "Vuepress快速入门",
      "frontmatter": {},
      "regularPath": "/frontend/vuepress/",
      "relativePath": "frontend/vuepress/README.md",
      "key": "v-14f6fb65",
      "path": "/frontend/vuepress/",
      "headers": [
        {
          "level": 2,
          "title": "vuepress官网",
          "slug": "vuepress官网"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "markdown快速入门",
      "frontmatter": {},
      "regularPath": "/frontend/vuepress/md%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html",
      "relativePath": "frontend/vuepress/md快速入门.md",
      "key": "v-78eca24a",
      "path": "/frontend/vuepress/md%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "1.代码块：",
          "slug": "_1-代码块"
        },
        {
          "level": 3,
          "title": "1.java代码块",
          "slug": "_1-java代码块"
        },
        {
          "level": 3,
          "title": "2.shell脚本",
          "slug": "_2-shell脚本"
        },
        {
          "level": 2,
          "title": "2.标题：",
          "slug": "_2-标题"
        },
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 2,
          "title": "3.字体",
          "slug": "_3-字体"
        },
        {
          "level": 2,
          "title": "4.引用：",
          "slug": "_4-引用"
        },
        {
          "level": 2,
          "title": "5.分割线：",
          "slug": "_5-分割线"
        },
        {
          "level": 2,
          "title": "//分割线",
          "slug": "分割线"
        },
        {
          "level": 2,
          "title": "6.图片插入",
          "slug": "_6-图片插入"
        },
        {
          "level": 2,
          "title": "7.超链接：",
          "slug": "_7-超链接"
        },
        {
          "level": 2,
          "title": "8.列表",
          "slug": "_8-列表"
        },
        {
          "level": 2,
          "title": "9.表格",
          "slug": "_9-表格"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "HTTP请求的Referrer-Policy字段",
      "frontmatter": {},
      "regularPath": "/frontend/vuepress/HTTP%E8%AF%B7%E6%B1%82%E7%9A%84Referrer-Policy%E5%AD%97%E6%AE%B5.html",
      "relativePath": "frontend/vuepress/HTTP请求的Referrer-Policy字段.md",
      "key": "v-6bad26ea",
      "path": "/frontend/vuepress/HTTP%E8%AF%B7%E6%B1%82%E7%9A%84Referrer-Policy%E5%AD%97%E6%AE%B5.html",
      "headers": [
        {
          "level": 2,
          "title": "HTTP请求的Referrer-Policy字段",
          "slug": "http请求的referrer-policy字段"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "使用docker部署vuepress",
      "frontmatter": {},
      "regularPath": "/frontend/vuepress/%E4%BD%BF%E7%94%A8docker%E9%83%A8%E7%BD%B2vuepress.html",
      "relativePath": "frontend/vuepress/使用docker部署vuepress.md",
      "key": "v-01fe0d70",
      "path": "/frontend/vuepress/%E4%BD%BF%E7%94%A8docker%E9%83%A8%E7%BD%B2vuepress.html",
      "headers": [
        {
          "level": 2,
          "title": "手动部署",
          "slug": "手动部署"
        },
        {
          "level": 2,
          "title": "自动部署",
          "slug": "自动部署"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "HTTP常见知识点",
      "frontmatter": {},
      "regularPath": "/network/http/HTTP%E5%B8%B8%E8%A7%81%E7%9F%A5%E8%AF%86%E7%82%B9.html",
      "relativePath": "network/http/HTTP常见知识点.md",
      "key": "v-b2baac44",
      "path": "/network/http/HTTP%E5%B8%B8%E8%A7%81%E7%9F%A5%E8%AF%86%E7%82%B9.html",
      "headers": [
        {
          "level": 2,
          "title": "1.HTTP常见的状态码",
          "slug": "_1-http常见的状态码"
        },
        {
          "level": 2,
          "title": "2.GET、POST、PUT、DELETE",
          "slug": "_2-get、post、put、delete"
        },
        {
          "level": 3,
          "title": "2.1 GET",
          "slug": "_2-1-get"
        },
        {
          "level": 3,
          "title": "2.2 POST",
          "slug": "_2-2-post"
        },
        {
          "level": 3,
          "title": "2.3 PUT",
          "slug": "_2-3-put"
        },
        {
          "level": 3,
          "title": "2.4 DELETE",
          "slug": "_2-4-delete"
        },
        {
          "level": 2,
          "title": "3.HTTP的优缺点",
          "slug": "_3-http的优缺点"
        },
        {
          "level": 3,
          "title": "3.1 性能问题（HTTP/1.1）",
          "slug": "_3-1-性能问题-http-1-1"
        },
        {
          "level": 2,
          "title": "4.HTTP与HTTPS的区别",
          "slug": "_4-http与https的区别"
        },
        {
          "level": 2,
          "title": "5.SSL/TSL建立的过程",
          "slug": "_5-ssl-tsl建立的过程"
        },
        {
          "level": 2,
          "title": "6.HTTP/1.1、HTTP/2、HTTP/3演变",
          "slug": "_6-http-1-1、http-2、http-3演变"
        },
        {
          "level": 3,
          "title": "HTTP/1.1相比于HTTP/1.0性能上的改进",
          "slug": "http-1-1相比于http-1-0性能上的改进"
        },
        {
          "level": 3,
          "title": "HTTP/2的优化",
          "slug": "http-2的优化"
        },
        {
          "level": 3,
          "title": "HTTP/2 存在的问题",
          "slug": "http-2-存在的问题"
        }
      ],
      "lastUpdated": "2022年5月6日 13:05",
      "lastUpdatedTimestamp": 1651813528000
    },
    {
      "title": "你好，HTTP!",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "h",
        "7": "t",
        "8": "t",
        "9": "p"
      },
      "regularPath": "/network/http/",
      "relativePath": "network/http/README.md",
      "key": "v-103622ea",
      "path": "/network/http/",
      "headers": [
        {
          "level": 2,
          "title": "你好，HTTP!",
          "slug": "你好-http"
        }
      ],
      "lastUpdated": "2022年4月21日 17:59",
      "lastUpdatedTimestamp": 1650535194000
    },
    {
      "title": "TCP详解",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "'",
        "7": "T",
        "8": "C",
        "9": "P",
        "10": "'"
      },
      "regularPath": "/network/tcp/TCP%E5%8D%8F%E8%AE%AE%E8%AF%A6%E8%A7%A3.html",
      "relativePath": "network/tcp/TCP协议详解.md",
      "key": "v-24195795",
      "path": "/network/tcp/TCP%E5%8D%8F%E8%AE%AE%E8%AF%A6%E8%A7%A3.html",
      "lastUpdated": "2022年5月2日 17:52",
      "lastUpdatedTimestamp": 1651485172000
    },
    {
      "title": "你好，TCP!",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "t",
        "7": "c",
        "8": "p"
      },
      "regularPath": "/network/tcp/",
      "relativePath": "network/tcp/README.md",
      "key": "v-b2aeebda",
      "path": "/network/tcp/",
      "headers": [
        {
          "level": 2,
          "title": "你好，TCP!",
          "slug": "你好-tcp"
        }
      ],
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    },
    {
      "title": "一些实用网站与工具",
      "frontmatter": {},
      "regularPath": "/tools/",
      "relativePath": "tools/README.md",
      "key": "v-6b6cedb0",
      "path": "/tools/",
      "lastUpdated": "2022年5月6日 13:05",
      "lastUpdatedTimestamp": 1651813528000
    },
    {
      "title": "收藏",
      "frontmatter": {},
      "regularPath": "/tools/%E6%94%B6%E8%97%8F.html",
      "relativePath": "tools/收藏.md",
      "key": "v-88a6e1b6",
      "path": "/tools/%E6%94%B6%E8%97%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "学习网站",
          "slug": "学习网站"
        },
        {
          "level": 2,
          "title": "技术社区",
          "slug": "技术社区"
        },
        {
          "level": 2,
          "title": "Emoji表情",
          "slug": "emoji表情"
        },
        {
          "level": 2,
          "title": "面试刷题",
          "slug": "面试刷题"
        }
      ],
      "lastUpdated": "2022年5月6日 13:05",
      "lastUpdatedTimestamp": 1651813528000
    },
    {
      "title": "Docker概述",
      "frontmatter": {},
      "regularPath": "/cloudnative/docker/",
      "relativePath": "cloudnative/docker/README.md",
      "key": "v-2aad01ea",
      "path": "/cloudnative/docker/",
      "lastUpdated": "2022年5月4日 22:45",
      "lastUpdatedTimestamp": 1651675528000
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "logo": "/assets/img/123.png",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "关于作者",
        "link": "/about"
      },
      {
        "text": "操作系统",
        "items": [
          {
            "text": "内存管理",
            "link": "/"
          },
          {
            "text": "进程管理",
            "link": "/"
          },
          {
            "text": "文件系统",
            "link": "/"
          }
        ]
      },
      {
        "text": "计算机网络",
        "items": [
          {
            "text": "HTTP协议",
            "link": "/network/http/HTTP常见知识点"
          },
          {
            "text": "TCP协议",
            "link": "/network/tcp/TCP协议详解"
          }
        ]
      },
      {
        "text": "前端",
        "items": [
          {
            "text": "Vuepress",
            "link": "/frontend/vuepress/"
          }
        ]
      },
      {
        "text": "后端",
        "items": [
          {
            "text": "Java",
            "link": "/backend/Java/Java的变量"
          },
          {
            "text": "设计模式",
            "link": "/backend/DesignPatterns/单例模式"
          },
          {
            "text": "MySQL",
            "link": "/backend/MySQL/MySQL简介"
          },
          {
            "text": "Redis",
            "link": "/backend/Redis/Redis的数据结构"
          },
          {
            "text": "Web服务器",
            "link": "/backend/webserver/Tomcat详解"
          },
          {
            "text": "Shell",
            "link": "/backend/Shell/Shell入门"
          }
        ]
      },
      {
        "text": "算法",
        "items": [
          {
            "text": "排序算法",
            "link": "/"
          }
        ]
      },
      {
        "text": "面试",
        "items": [
          {
            "text": "JVM八股文",
            "link": "/"
          }
        ]
      },
      {
        "text": "云原生",
        "items": [
          {
            "text": "docker",
            "link": "/cloudnative/docker/Docker入门"
          },
          {
            "text": "kubernetes",
            "link": "/cloudnative/kubernetes/kubernetes入门"
          }
        ]
      },
      {
        "text": "摸鱼",
        "items": [
          {
            "text": "bilibili",
            "link": "https://www.bilibili.com/"
          },
          {
            "text": "douyu",
            "link": "https://www.douyu.com/"
          },
          {
            "text": "抓鱼鸭",
            "link": "http://zhuayuya.com/"
          }
        ]
      },
      {
        "text": "收藏",
        "link": "/tools/收藏"
      }
    ],
    "sidebar": {
      "/backend/DesignPatterns/": [
        "",
        "单例模式"
      ],
      "/backend/Java/": [
        "",
        "Java的变量",
        "Java中的数组",
        "面向对象",
        "static关键字",
        "==和equals的区别",
        "Java集合",
        "Java多线程"
      ],
      "/backend/MySQL/": [
        "",
        "MySQL简介"
      ],
      "/backend/Redis/": [
        "",
        "高可用",
        "基础架构",
        "数据结构"
      ],
      "/backend/Shell/": [
        "",
        "Shell入门"
      ],
      "/backend/webserver/": [
        "",
        "Tomcat详解"
      ],
      "/interview/JVM/": [
        ""
      ],
      "/frontend/vuepress/": [
        "",
        "md快速入门",
        "使用docker部署vuepress",
        "HTTP请求的Referrer-Policy字段"
      ],
      "/cloudnative/docker/": [
        "",
        "Docker入门"
      ],
      "/cloudnative/kubernetes/": [
        "",
        "kubernetes入门"
      ],
      "/network/http/": [
        "",
        "HTTP常见知识点"
      ],
      "/network/tcp/": [
        "",
        "TCP协议详解"
      ],
      "/OperationSystem/": [
        ""
      ],
      "/tools/": [
        "",
        "收藏"
      ]
    }
  }
}