/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "somnus",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "somnus-wang"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "vuepress介绍"
      }
    ]
  ],
  "pages": [
    {
      "title": "多线程",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "'",
        "7": "多",
        "8": "线",
        "9": "程",
        "10": "'"
      },
      "regularPath": "/Java/Java%E5%A4%9A%E7%BA%BF%E7%A8%8B.html",
      "relativePath": "Java/Java多线程.md",
      "key": "v-b832ecce",
      "path": "/Java/Java%E5%A4%9A%E7%BA%BF%E7%A8%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        }
      ],
      "lastUpdated": "2022年4月15日星期五中午11点44分",
      "lastUpdatedTimestamp": 1649994291000
    },
    {
      "title": "Hello,Java!",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "j",
        "7": "a",
        "8": "v",
        "9": "a"
      },
      "regularPath": "/Java/",
      "relativePath": "Java/README.md",
      "key": "v-58602bfe",
      "path": "/Java/",
      "headers": [
        {
          "level": 2,
          "title": "Hello,Java!",
          "slug": "hello-java"
        }
      ],
      "lastUpdated": "2022年4月15日星期五中午11点44分",
      "lastUpdatedTimestamp": 1649994291000
    },
    {
      "title": "Java集合",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "'",
        "7": "J",
        "8": "a",
        "9": "v",
        "10": "a",
        "11": "集",
        "12": "合",
        "13": "'"
      },
      "regularPath": "/Java/Java%E9%9B%86%E5%90%88.html",
      "relativePath": "Java/Java集合.md",
      "key": "v-6960f2c2",
      "path": "/Java/Java%E9%9B%86%E5%90%88.html",
      "lastUpdated": "2022年4月15日星期五中午11点44分",
      "lastUpdatedTimestamp": 1649994291000
    },
    {
      "title": "Hello,Redis!",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "r",
        "7": "e",
        "8": "d",
        "9": "i",
        "10": "s"
      },
      "regularPath": "/Redis/",
      "relativePath": "Redis/README.md",
      "key": "v-782676b0",
      "path": "/Redis/",
      "headers": [
        {
          "level": 2,
          "title": "Hello,Redis!",
          "slug": "hello-redis"
        }
      ],
      "lastUpdated": "2022年4月15日星期五中午11点44分",
      "lastUpdatedTimestamp": 1649994291000
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Somnus Space",
        "tagline": "somnus的个人笔记",
        "actionText": "快速开始 →",
        "actionLink": "/about/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "SCU Licensed | Copyright © 2022-present Somnus-wang & Lj-Z"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-60e69aca",
      "path": "/",
      "lastUpdated": "2022年4月15日星期五中午11点44分",
      "lastUpdatedTimestamp": 1649994291000
    },
    {
      "title": "面向对象",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "'",
        "7": "O",
        "8": "O",
        "9": "P",
        "10": "'"
      },
      "regularPath": "/Java/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html",
      "relativePath": "Java/面向对象.md",
      "key": "v-3239f1db",
      "path": "/Java/%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html",
      "lastUpdated": "2022年4月15日星期五中午11点44分",
      "lastUpdatedTimestamp": 1649994291000
    },
    {
      "title": "Redis数据结构",
      "frontmatter": {},
      "regularPath": "/Redis/Redis%E7%9A%84%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html",
      "relativePath": "Redis/Redis的数据结构.md",
      "key": "v-199dc994",
      "path": "/Redis/Redis%E7%9A%84%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html",
      "lastUpdated": "2022年4月15日星期五中午11点44分",
      "lastUpdatedTimestamp": 1649994291000
    },
    {
      "title": "HTTP常见知识点",
      "frontmatter": {},
      "regularPath": "/http/HTTP%E5%B8%B8%E8%A7%81%E7%9F%A5%E8%AF%86%E7%82%B9.html",
      "relativePath": "http/HTTP常见知识点.md",
      "key": "v-35fceb26",
      "path": "/http/HTTP%E5%B8%B8%E8%A7%81%E7%9F%A5%E8%AF%86%E7%82%B9.html",
      "headers": [
        {
          "level": 2,
          "title": "1.HTTP常见的状态码",
          "slug": "_1-http常见的状态码"
        },
        {
          "level": 2,
          "title": "2.GET、POST、PUT、DELETE",
          "slug": "_2-get、post、put、delete"
        },
        {
          "level": 3,
          "title": "2.1 GET",
          "slug": "_2-1-get"
        },
        {
          "level": 3,
          "title": "2.2 POST",
          "slug": "_2-2-post"
        },
        {
          "level": 3,
          "title": "2.3 PUT",
          "slug": "_2-3-put"
        },
        {
          "level": 3,
          "title": "2.4 DELETE",
          "slug": "_2-4-delete"
        },
        {
          "level": 2,
          "title": "3.HTTP的优缺点",
          "slug": "_3-http的优缺点"
        },
        {
          "level": 3,
          "title": "3.1 性能问题（HTTP/1.1）",
          "slug": "_3-1-性能问题-http-1-1"
        },
        {
          "level": 2,
          "title": "4.HTTP与HTTPS的区别",
          "slug": "_4-http与https的区别"
        },
        {
          "level": 2,
          "title": "5.SSL/TSL建立的过程",
          "slug": "_5-ssl-tsl建立的过程"
        },
        {
          "level": 2,
          "title": "6.HTTP/1.1、HTTP/2、HTTP/3演变",
          "slug": "_6-http-1-1、http-2、http-3演变"
        },
        {
          "level": 3,
          "title": "HTTP/1.1相比于HTTP/1.0性能上的改进",
          "slug": "http-1-1相比于http-1-0性能上的改进"
        },
        {
          "level": 3,
          "title": "HTTP/2的优化",
          "slug": "http-2的优化"
        },
        {
          "level": 3,
          "title": "HTTP/2 存在的问题",
          "slug": "http-2-存在的问题"
        }
      ],
      "lastUpdated": "2022年4月15日星期五中午11点44分",
      "lastUpdatedTimestamp": 1649994291000
    },
    {
      "title": "TCP详解",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "'",
        "7": "T",
        "8": "C",
        "9": "P",
        "10": "'"
      },
      "regularPath": "/http/TCP%E5%8D%8F%E8%AE%AE%E8%AF%A6%E8%A7%A3.html",
      "relativePath": "http/TCP协议详解.md",
      "key": "v-2a45a31c",
      "path": "/http/TCP%E5%8D%8F%E8%AE%AE%E8%AF%A6%E8%A7%A3.html",
      "lastUpdated": "2022年4月15日星期五中午11点44分",
      "lastUpdatedTimestamp": 1649994291000
    },
    {
      "title": "你好，HTTP!",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "h",
        "7": "t",
        "8": "t",
        "9": "p"
      },
      "regularPath": "/http/",
      "relativePath": "http/README.md",
      "key": "v-1907ae84",
      "path": "/http/",
      "headers": [
        {
          "level": 2,
          "title": "你好，HTTP!",
          "slug": "你好-http"
        }
      ],
      "lastUpdated": "2022年4月15日星期五中午11点44分",
      "lastUpdatedTimestamp": 1649994291000
    },
    {
      "title": "markdown快速入门（typora）",
      "frontmatter": {},
      "regularPath": "/markdown/md%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html",
      "relativePath": "markdown/md快速入门.md",
      "key": "v-15fec9c2",
      "path": "/markdown/md%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "1.代码块：",
          "slug": "_1-代码块"
        },
        {
          "level": 3,
          "title": "1.java代码块",
          "slug": "_1-java代码块"
        },
        {
          "level": 3,
          "title": "2.shell脚本",
          "slug": "_2-shell脚本"
        },
        {
          "level": 2,
          "title": "2.标题：",
          "slug": "_2-标题"
        },
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 2,
          "title": "3.字体",
          "slug": "_3-字体"
        },
        {
          "level": 2,
          "title": "4.引用：",
          "slug": "_4-引用"
        },
        {
          "level": 2,
          "title": "5.分割线：",
          "slug": "_5-分割线"
        },
        {
          "level": 2,
          "title": "//分割线",
          "slug": "分割线"
        },
        {
          "level": 2,
          "title": "6.图片插入",
          "slug": "_6-图片插入"
        },
        {
          "level": 2,
          "title": "7.超链接：",
          "slug": "_7-超链接"
        },
        {
          "level": 2,
          "title": "8.列表",
          "slug": "_8-列表"
        },
        {
          "level": 2,
          "title": "9.表格",
          "slug": "_9-表格"
        }
      ],
      "lastUpdated": "2022年4月15日星期五中午11点44分",
      "lastUpdatedTimestamp": 1649994291000
    },
    {
      "title": "关于我",
      "frontmatter": {
        "0": "n",
        "1": "a",
        "2": "v",
        "3": "b",
        "4": "a",
        "5": "r",
        "6": ":",
        "7": "f",
        "8": "a",
        "9": "l",
        "10": "s",
        "11": "e"
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-5c3f2240",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        }
      ],
      "lastUpdated": "2022年4月15日星期五中午11点44分",
      "lastUpdatedTimestamp": 1649994291000
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "logo": "/assets/img/123.png",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "关于作者",
        "link": "/about"
      },
      {
        "text": "计算机网络",
        "items": [
          {
            "text": "HTTP协议",
            "link": "/http/HTTP常见知识点"
          },
          {
            "text": "TCP协议",
            "link": "/http/TCP协议详解"
          }
        ]
      },
      {
        "text": "Java",
        "items": [
          {
            "text": "面向对象",
            "link": "/Java/面向对象"
          },
          {
            "text": "Java集合",
            "link": "/Java/Java集合"
          },
          {
            "text": "Java多线程",
            "link": "/Java/Java多线程"
          }
        ]
      },
      {
        "text": "Redis",
        "items": [
          {
            "text": "Redis数据结构",
            "link": "/Redis/Redis的数据结构"
          }
        ]
      },
      {
        "text": "MySQL",
        "items": [
          {
            "text": "MySQL的索引",
            "link": "/"
          }
        ]
      },
      {
        "text": "摸鱼",
        "items": [
          {
            "text": "bilibili",
            "link": "https://www.bilibili.com/"
          },
          {
            "text": "douyu",
            "link": "https://www.douyu.com/"
          },
          {
            "text": "DOTA2",
            "link": "https://www.dota2.com/"
          }
        ]
      }
    ],
    "sidebar": [
      "",
      "about",
      {
        "title": "markdown基本语法",
        "path": "/markdown/md快速入门",
        "collapsable": false,
        "sidebarDepth": 1
      },
      {
        "title": "HTTP详解",
        "path": "/http/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/http/HTTP常见知识点"
        ]
      },
      {
        "title": "Java",
        "path": "/Java/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/Java/面向对象",
          "/Java/Java集合",
          "/Java/Java多线程"
        ]
      },
      {
        "title": "Redis详解",
        "path": "/Redis/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/Redis/Redis的数据结构"
        ]
      }
    ]
  }
}